// web-react/src/components/Questions.js
import React from 'react'
import Question from "./Question";

const questions = (props) => (
    <div id="questions">
        <p>{props.questions[props.current].question}</p>
        <form>
            {props.questions[props.current].answers
                .map((answer, index) => <Question id={index+1} key={index} text={answer} clicked={props.answerClicked}/>
                )}
        </form>
    </div>
);

export default questions;

// web-vue/src/components/Questions.vue
<template>
  <div id="questions">
    <p>{{ questions[current].question }}</p>
    <form>
      <question v-for="(answer, index) in questions[current].answers"
        :key="index"
        :val="index+1"
        :text="answer" @questionClicked="questionClicked($event)" />
    </form>
  </div>
</template>

<script>
  import Question from './Question'

  export default {
    props: ['questions', 'current', 'selected'],
    components: {
      question: Question
    },
    methods: {
      questionClicked($event) {
        this.$emit('questionClicked', $event);
      }
    }
  }
</script>

<style scoped>
  #questions {
    padding: 20px 10px;
  }
</style>
