// web-vue/src/components/Score.vue
<template>
  <div>
    <h1>Fiddle Faddle</h1>
    <div id="score">
      <div id="level">Level: 1</div>
      <div id="thescore">Score: {{ score }} / {{ current }}</div>
    </div>
  </div>
</template>

<script>
  export default {
    props: {
      score: Number,
      current: Number
    }
  }
</script>

<style scoped>
  #score {
    padding: 15px 10px;
    font-weight: bold;
  }

  #score div {
    float: left;
    width: 50%;
  }

  #thescore {
    text-align: right;
  }
</style>

// web-react/src/components/Score.js
import React from 'react'
import Wrapper from "../hoc/Wrapper";

const score = (props) => (
    <Wrapper>
        <h1>Fiddle Faddle</h1>
        <div id="score">
            <div id="level">Level: 1</div>
            <div id="thescore">Score: {props.score} / {props.current}</div>
        </div>
    </Wrapper>
);

export default score;
